### ISSUE TITLE
Remove border around page content in Finder preview/exported HTML file?

### ISSUE THREAD

**Issue by keriheuer** [sbarex/QLMarkdown#126] opened 2023-12-18 17:09 UTC
Is there a way to remove the border line for the Finder preview? I just downloaded QLMarkdown so am still learning how to use it but I'm a little confused on the behavior of this border. Specifically, if my Finder window is too large, then the preview of the .md file puts a gray border around the content and adds a big margin on the left/right hand sides. However, if Finder is less than ~2/3 my window screen, then there's no border or extra margin.

Is there somewhere in QLMarkdown's settings that I could change this? Or is this behavior hard-coded into how the preview renders? I would like my .md file's content to always not have the border regardless of the Finder window size, especially since this behavior carries over to the exported HTML file when opened in Safari. 

Screenshots of how the border disappears when the Finder window size becomes less than some threshold size. 

<img width="1512" alt="Screenshot 2023-12-18 at 12 08 02 PM" src="https://github.com/sbarex/QLMarkdown/assets/54902150/d1cd10fd-b59d-44e0-88cc-2632138a6f2a">
<img width="1512" alt="Screenshot 2023-12-18 at 12 08 16 PM" src="https://github.com/sbarex/QLMarkdown/assets/54902150/8daf662e-9297-45dc-9e21-dd5093993c4f">

**Comment by setanarut** [comment] 2023-12-18 21:46
duplicate of https://github.com/sbarex/QLMarkdown/issues/113

The whole theme can be changed with a CSS file. I explained it in this link.

**Closed** 2024-08-05 19:00 UTC
