### ISSUE TITLE
WebP, SVG and Placeholder Video Thumbnail Support.

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#49] opened 2021-01-18 01:44 UTC
I know, Github's `README.MD` does not support inline SVG , WebP and videos. Maybe features specific to macOS can be considered.

### The Quick Look HTML preview supports the following;

- SVG
- WebP (Animated and Static)
- Placeholder Video Thumbnail

### QLMarkdown **cannot** display the following;

**Inline HTML**
- WebP (Animated and Static) - `<img src="image.webp" alt="">`
- Placeholder Video Thumbnail - `<source src="video.mov" type="video/mp4">`

**Markdown**
- SVG - `![SVG](image.svg)`
- WebP - `![WEBP](image.webp)`

> **Note**:  Embedded webp is not displayed. `<img src="data:image/webp;base64........`

<img width="1226" alt="Ekran Resmi 2021-01-18 03 54 38" src="https://user-images.githubusercontent.com/36481442/104863427-dd480700-5946-11eb-81ed-a50765060458.png">

**Comment by sbarex** [comment] 2021-01-18 21:37
The .svg and .webp images are in the same folder of the markdown file?
On my mac the svg and webp preview works.

**Comment by hazarek** [comment] 2021-01-18 22:06
> The .svg and .webp images are in the same folder of the markdown file?
> On my mac the svg and webp preview works.
> 
> In the app editor if you write by hand the code the images are searched from the resource bundle of the app. Otherwise if you open an .md file, the basedir is the folder of the .md file.

Yes, The .svg and .webp images are in the same folder. I tested every condition, it doesn't work for me.

**Comment by sbarex** [comment] 2021-01-19 08:04
Can you share the .md and .svg file?

**Comment by hazarek** [comment] 2021-01-19 17:27
@sbarex https://yadi.sk/d/HZ0pKfqjy0LO-g

**Comment by sbarex** [comment] 2021-01-20 19:25
Please try release 17.

Regarding the preview of the videos I don't think to implement it. Security restrictions  prevent you from accessing video files from the quick look preview.
An extension should be created that analyzes the .md file looking for html code containing a video, reads the file, obtains the preview and inserts it in the formatted html code... 
Moreover Apple does not directly manage many video formats (webm, mkv, avi, ...) and you should use external libraries such as ffmpeg.
A lot of work for a non-standard functionality for the .md language.

**Comment by hazarek** [comment] 2021-01-20 19:44
> Please try release 17.
> 
> Regarding the preview of the videos I don't think to implement it. Security restrictions prevent you from accessing video files from the quick look preview.
> An extension should be created that analyzes the .md file looking for html code containing a video, reads the file, obtains the preview and inserts it in the formatted html code...
> Moreover Apple does not directly manage many video formats (webm, mkv, avi, ...) and you should use external libraries such as ffmpeg.
> A lot of work for a non-standard functionality for the .md language.

Thanks, video thumbnails is not important. SVG fixed but webp is still not displayed. `![test](./webp_test.webp)`

**Comment by hazarek** [comment] 2021-01-20 19:48
Quick Look doesn't play animated webp by default. I think QLMarkdown should show WebP.

**Comment by sbarex** [comment] 2021-01-20 19:52
In the terminal, what is the output of this command?
```
$ file --mime-type PATH_OF_WEBP_FILE
```
It should be `image/webp`.
Also, if the QLMarkdown app in on the Applications folder try this command:
```bash
file --mime-type -m /Applications/QLMarkdown.app/Contents/Resources/magic.mgc PATH_OF_WEBP_FILE
```

The result should always be `image/webp`.

Can you provide a webp animated file?

**Comment by hazarek** [comment] 2021-01-20 20:42
```
➜  Desktop file --mime-type ./webp_test.webp                   
./webp_test.webp: image/webp
➜  Desktop file --mime-type -m /Applications/QLMarkdown.app/Contents/Resources/magic.mgc ./webp_test.webp 
./webp_test.webp: image/webp
```
webp images
https://developers.google.com/speed/webp/gallery1

**Comment by sbarex** [comment] 2021-01-21 08:23
on release 18 should be fixed (also support for animated .webp).

**Closed** 2021-01-21 17:27 UTC

**Comment by hazarek** [comment] 2021-02-13 23:24
@sbarex SVG works if this option is selected. but this is not inline HTML code -> `![test](./test.svg)`.  This is a valid Markdown syntax. This is confusing for the end user.

<img width="212" alt="Ekran Resmi 2021-02-14 02 17 47" src="https://user-images.githubusercontent.com/36481442/107864241-41d58380-6e6b-11eb-9dc9-559562dad7c8.png">

**Comment by sbarex** [comment] 2021-02-14 08:37
This behavior is caused by cmark. 

When html content is not allowed, it automatically performs a series of extra checks in search of dangerous content. For the images, it checks their url, removing any it thinks are not safe. In the case of the `data:` scheme (used to embed the image file inside the html output preventing the security limitation of the Quick Look engine) only these mime types are allowed: `image/png` `image/gif`, `image/jpeg`, `image/webp`.

**Comment by hazarek** [comment] 2021-02-14 16:35
I think, you should write this in the documentation. --> "This option must be selected for SVG preview"  <img width="212" alt="Ekran Resmi 2021-02-14 02 17 47" src="https://user-images.githubusercontent.com/36481442/107864241-41d58380-6e6b-11eb-9dc9-559562dad7c8.png">
